project:
  type: website
  output-dir: _site
website:
  title: "Thom Volker"
  navbar:
    left:
      - href: blog.qmd
        text: blog
      - href: software.qmd
        text: software
      - href: teaching/index.qmd
        text: teaching
      - href: talks/index.qmd
        text: talks
      - href: https://github.com/thomvolker
        text: code
        target: _blank
    right:
      - text: about
        href: about.qmd
      - text: "{{< iconify academicons cv-square >}}"
        href: files/cv/cv.pdf
        target: _blank
      - icon: strava
        href: https://www.strava.com/athletes/34188992
        target: _blank
format:
  html:
    theme:
      light:
        - flatly
        - styles-light.scss
      dark:
        - styles-dark.scss
    highlight-style: dracula
    css: styles.css
    toc: true
execute:
  freeze: auto



